### ISSUE TITLE
vitest/lower-case-title autofix is broken

### ISSUE THREAD

**Issue by qeleb** [veritem/eslint-plugin-vitest#37]
When `vitest/lower-case-title` is enabled, the autofixer adds a bunch of spaces between letters. Please fix?

**Comment by veritem** [comment]
Would you mind sending a repro?

**Comment by qeleb** [comment]
I haven’t got time to send over a repro today & my issue is in a private repo.

this test is passing? i’ve had this same bug since 0.0.20.

I’ve also found that expect-expect errors on run (something about length of property undefined), and no-identical-title seems not to do anything

**Comment by veritem** [comment]
@qeleb, those were fixed a few weeks ago.  update the package to the latest version

**Comment by qeleb** [comment]
i’m using latest

**Comment by veritem** [comment]
Hi, let me know if you're still experiencing the same issue. If that's the case, feel free to re-open this

**Comment by qeleb** [comment]
Hi! Yes, please reopen this issue.

Unfortunately, all of these problems still exist in 0.0.30.
I've just done a test this morning to verify.

It has improved massively since I got this eslint plugin weeks ago, but some are still not working, so my eslint config looks like this:
```js
env: { 'vitest-globals/env': true },
rules: {
  'vitest/consistent-test-it': ['error', { fn: 'it' }],
  //'vitest/expect-expect': 'error', // broken
  //'vitest/lower-case-title': 'warn', //autofix broken
  'vitest/max-nested-describe': ['error', { max: 3 }],
  'vitest/no-conditional-tests': 'error',
  'vitest/no-focused-tests': 'warn',
  //'vitest/no-identical-title': 'error', // broken
  'vitest/no-skipped-tests': 'warn',
},
```

`vitest/expect-expect` & `vitest/no-identical-title` don't work at all, but `lower-case-title` is really close to working.
It correctly identifies tests with uppercase letters, but autofix litters the titles with extra spaces.

Example:
`[GET] /404: missing route` => `[ g e t] /404: missing route`

**Comment by veritem** [comment]
Please use the latest version, I'm not sure why this is still occurring for you here is an example https://github.com/veritem/eslint-plugin-vitest/tree/main/fixtures

**Comment by qeleb** [comment]
@veritem 
try making it say “[test]: this is a test”
i think some characters like the square bracket are breaking it.

**Comment by qeleb** [comment]
then why is the current version adding a bunch of spaces on autofix? something is not adding up…

**Comment by veritem** [comment]
I haven't seen this may be an example would help me fix it asp.  I have tried this `[TEST]: This is a Test` it doesn't do anything to the text.
